"""Persistent CoPE state engine and strictly paired main-comparison infrastructure."""

from .errors import CoPEError, InvariantError, SchemaError, TransitionError
from .operations import apply_patch
from .recovery import revalidate_slot, stable_validation_id
from .replay import replay
from .schema import (
    SCHEMA_VERSION,
    AppliedPatch,
    ConstraintMode,
    ConstraintSlot,
    ConstraintSource,
    ConstraintState,
    Demote,
    EventRecord,
    EventSource,
    Expire,
    Insert,
    Override,
    Patch,
    PatchContext,
    Restore,
    Revalidate,
    RevalidationResult,
    Suspend,
    TransitionResult,
    ValidationIssue,
    ValidationRecord,
    ValidationReport,
)
from .serialization import (
    canonical_state_hash,
    canonical_state_json,
    deserialize_patch,
    deserialize_state,
    serialize_patch,
    serialize_state,
)
from .validator import validate_state
from .types import (
    METHOD_NAMES,
    PATCH_OPERATION_TYPES,
    FullStateOutput,
    MethodDecision,
    PatchOperation,
    PatchOutput,
    RecoveryInput,
)

__all__ = [
    "METHOD_NAMES",
    "PATCH_OPERATION_TYPES",
    "SCHEMA_VERSION",
    "AppliedPatch",
    "CoPEError",
    "ConstraintMode",
    "ConstraintSlot",
    "ConstraintSource",
    "ConstraintState",
    "Demote",
    "EventRecord",
    "EventSource",
    "Expire",
    "FullStateOutput",
    "Insert",
    "InvariantError",
    "MethodDecision",
    "Override",
    "Patch",
    "PatchOperation",
    "PatchOutput",
    "PatchContext",
    "RecoveryInput",
    "Restore",
    "Revalidate",
    "RevalidationResult",
    "SchemaError",
    "Suspend",
    "TransitionError",
    "TransitionResult",
    "ValidationIssue",
    "ValidationRecord",
    "ValidationReport",
    "apply_patch",
    "canonical_state_hash",
    "canonical_state_json",
    "deserialize_patch",
    "deserialize_state",
    "replay",
    "revalidate_slot",
    "serialize_patch",
    "serialize_state",
    "stable_validation_id",
    "validate_state",
]
